# Generated by Django 5.0.2 on 2024-02-27 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolioback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='imagen',
            field=models.ImageField(upload_to='portafolio/imagen/'),
        ),
    ]
